site_name: Data Science & ML Demos
copyright: Copyright &copy; 2021-2022 Alex Ioannides
repo_url: https://github.com/AlexIoannides/data-science-and-ml-notebook
repo_name: alexioannides/data-science-and-ml-notebook
docs_dir: demos
site_dir: .github-pages-site

nav:
  - About: README.md
  - Data Science:
    - PyTorch:
      - pytorch/README.md
      - Tensor Manipulation: pytorch/tensors.ipynb
      - Datasets: pytorch/datasets.ipynb
  - ML Engineering:
    - DVC:
      - dvc/README.md
      - Demo Requirements: dvc/docs/demo_requirements.md
      - Dataset Versioning: dvc/data_and_model_versioning.ipynb
    - DVC Pipelines:
      - dvc-pipelines/README.md
      - Demo Requirements: dvc-pipelines/docs/demo_requirements.md
      - Example Pipeline: dvc-pipelines/docs/example_pipeline.md
      - Tracking Pipeline Artefacts: dvc-pipelines/dvc_pipelines.ipynb
    - Dagster:
      - dagster/README.md
      - Demo Requirements: dagster/docs/demo_requirements.md 
      - Example Pipeline: dagster/docs/example_pipeline.md
      - Testing Pipelines: dagster/docs/testing_pipelines.md
      - Repos & Worskpaces: dagster/docs/repos_and_workspaces.md
  - Data Engineering:
    - Ibis:
      - ibis/README.md
      - Demo Requirements: ibis/docs/demo_requirements.md
      - Intertcting with Data: ibis/ibis_introduction.ipynb

plugins:
  - mkdocs-jupyter:
      include: ["*.ipynb"]

theme:
  name: material
  palette:
    scheme: slate
    primary: green
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
  icon:
    logo: octicons/terminal-24

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AlexIoannides
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ioannides_alex
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexioannides/